# Generated by Django 4.2.1 on 2023-06-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.category')),
            ],
        ),
    ]
